spring:
  cloud:
    config:
      server:
        git:
          uri: http://192.196.1.139/config/cloudappconfig
          search-paths: test
          username: lisq
          password: li123456

server:
  port: 8888